/**
 * Manifest loading + defensive validation.
 *
 * The manifest is generated by `scripts/build-manifest.ts` at build time and
 * served as a static JSON file. It is *build output*, so the client refuses to
 * crash on a partial / stale / hand-edited file: anything unusable is skipped
 * with a warning, and only a fundamentally broken shape becomes an error state
 * with a friendly Chinese message.
 */

import {
  MANIFEST_VERSION,
  type DateGroup,
  type LayerNode,
  type LayerRect,
  type Manifest,
  type PreviewAssets,
  type WorkEntry,
} from '../../shared/manifest';
import { joinUrl, normalizeBase } from '../../shared/paths';

export type ManifestStatus = 'loading' | 'ready' | 'empty' | 'error';

export interface ManifestState {
  status: ManifestStatus;
  manifest: Manifest | null;
  error: string | null;
  /** Re-run the fetch (used by the error state's retry button). */
  reload: () => void;
}

export const MANIFEST_PATH = 'generated/manifest.json';

export const MANIFEST_EMPTY_MESSAGE =
  '还没有作品。把 PSD 放进 works/YYYY-MM-DD/ 目录并重新构建，这里就会自动出现缩略图与查看入口。';

export const MANIFEST_MISSING_MESSAGE =
  '作品清单尚未生成（generated/manifest.json 不存在）。请先运行 npm run manifest，再刷新页面。';

/** Site-absolute URL of the generated manifest, honoring Vite's `base`. */
export function manifestUrl(base: string | undefined = import.meta.env.BASE_URL): string {
  return joinUrl(normalizeBase(base), MANIFEST_PATH);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function asFinite(value: unknown): number | undefined {
  if (typeof value === 'number' && Number.isFinite(value)) return value;
  if (typeof value === 'string' && value.trim() !== '') {
    const parsed = Number(value);
    if (Number.isFinite(parsed)) return parsed;
  }
  return undefined;
}

function asString(value: unknown): string | undefined {
  return typeof value === 'string' ? value : undefined;
}

function asBool(value: unknown): boolean | undefined {
  return typeof value === 'boolean' ? value : undefined;
}

function asArray(value: unknown): unknown[] {
  return Array.isArray(value) ? value : [];
}

function clamp01(value: number): number {
  return Math.min(1, Math.max(0, value));
}

function parseRect(raw: unknown): LayerRect | null {
  if (!isRecord(raw)) return null;
  const left = asFinite(raw.left);
  const top = asFinite(raw.top);
  const right = asFinite(raw.right);
  const bottom = asFinite(raw.bottom);
  if (left === undefined || top === undefined || right === undefined || bottom === undefined) return null;
  return { left, top, right, bottom };
}

function parseLayer(raw: unknown, warnings: string[], path: string): LayerNode | null {
  if (!isRecord(raw)) {
    warnings.push(`跳过非法图层（${path}）：不是对象`);
    return null;
  }
  const name = asString(raw.name);
  const rect = parseRect(raw.rect);
  if (name === undefined || !rect) {
    warnings.push(`跳过非法图层（${path}）：缺少 name 或 rect`);
    return null;
  }
  const childrenRaw = asArray(raw.children);
  const children = childrenRaw
    .map((child, index) => parseLayer(child, warnings, `${path}.${index}`))
    .filter((child): child is LayerNode => child !== null);
  const isGroup = asBool(raw.isGroup) ?? children.length > 0;
  const hidden = asBool(raw.hidden) ?? false;
  const opacity = clamp01(asFinite(raw.opacity) ?? 1);
  const blendMode = asString(raw.blendMode) ?? 'normal';
  const hasImage = asBool(raw.hasImage) ?? !isGroup;
  const kind = asString(raw.kind);
  const note = asString(raw.note);
  return {
    name,
    hidden,
    opacity,
    blendMode,
    rect,
    hasImage: isGroup ? false : hasImage,
    isGroup,
    ...(kind ? { kind } : {}),
    ...(note ? { note } : {}),
    ...(children.length > 0 ? { children } : {}),
  };
}

function parsePreview(raw: unknown, fallbackWidth: number, fallbackHeight: number): PreviewAssets {
  const record = isRecord(raw) ? raw : {};
  const thumbWidth = asFinite(record.thumbWidth) ?? Math.max(1, Math.round(fallbackWidth));
  const thumbHeight = asFinite(record.thumbHeight) ?? Math.max(1, Math.round(fallbackHeight));
  const displayWidth = asFinite(record.displayWidth) ?? Math.max(1, Math.round(fallbackWidth));
  const displayHeight = asFinite(record.displayHeight) ?? Math.max(1, Math.round(fallbackHeight));
  return {
    thumb: asString(record.thumb) ?? '',
    display: asString(record.display) ?? '',
    thumbWidth: Math.max(1, Math.round(thumbWidth)),
    thumbHeight: Math.max(1, Math.round(thumbHeight)),
    displayWidth: Math.max(1, Math.round(displayWidth)),
    displayHeight: Math.max(1, Math.round(displayHeight)),
  };
}

function countLayers(layers: readonly LayerNode[]): number {
  let total = 0;
  for (const layer of layers) {
    total += 1;
    if (layer.children) total += countLayers(layer.children);
  }
  return total;
}

function parseWork(raw: unknown, warnings: string[], path: string): WorkEntry | null {
  if (!isRecord(raw)) {
    warnings.push(`跳过非法作品（${path}）：不是对象`);
    return null;
  }
  const name = asString(raw.name);
  const psd = asString(raw.psd);
  const width = asFinite(raw.width);
  const height = asFinite(raw.height);
  if (!name || !psd || width === undefined || height === undefined || width <= 0 || height <= 0) {
    warnings.push(`跳过非法作品（${path}）：缺少 name/psd/width/height`);
    return null;
  }
  const layers = asArray(raw.layers)
    .map((child, index) => parseLayer(child, warnings, `${path}.layers[${index}]`))
    .filter((child): child is LayerNode => child !== null);
  const index = asFinite(raw.index) ?? Number.parseInt(name, 10);
  return {
    index: Number.isFinite(index) ? index : 0,
    name,
    psd,
    bytes: Math.max(0, asFinite(raw.bytes) ?? 0),
    width: Math.round(width),
    height: Math.round(height),
    preview: parsePreview(raw.preview, width, height),
    layerCount: Math.max(0, Math.round(asFinite(raw.layerCount) ?? countLayers(layers))),
    layers,
  };
}

export interface ParseManifestResult {
  manifest: Manifest | null;
  error: string | null;
  warnings: string[];
}

/**
 * Validate an unknown JSON value into a {@link Manifest}. Invalid works/layers
 * are dropped (with a warning) instead of poisoning the whole gallery.
 */
export function parseManifest(raw: unknown): ParseManifestResult {
  const warnings: string[] = [];
  if (!isRecord(raw)) {
    return { manifest: null, error: '作品清单格式不正确：顶层不是 JSON 对象。', warnings };
  }
  const version = asFinite(raw.version);
  if (version !== MANIFEST_VERSION) {
    return {
      manifest: null,
      error: `作品清单版本不匹配（期望 ${MANIFEST_VERSION}，实际 ${String(raw.version ?? '缺失')}），请重新构建网站。`,
      warnings,
    };
  }
  if (!Array.isArray(raw.groups)) {
    return { manifest: null, error: '作品清单格式不正确：缺少 groups 数组。', warnings };
  }

  const groups: DateGroup[] = [];
  for (const [groupIndex, groupRaw] of asArray(raw.groups).entries()) {
    if (!isRecord(groupRaw)) {
      warnings.push(`跳过非法日期分组 #${groupIndex}：不是对象`);
      continue;
    }
    const date = asString(groupRaw.date);
    if (!date) {
      warnings.push(`跳过非法日期分组 #${groupIndex}：缺少 date`);
      continue;
    }
    const works = asArray(groupRaw.works)
      .map((workRaw, workIndex) => parseWork(workRaw, warnings, `${date}[${workIndex}]`))
      .filter((work): work is WorkEntry => work !== null)
      .sort((a, b) => a.index - b.index || a.name.localeCompare(b.name));
    if (works.length === 0) continue;
    groups.push({ date, works });
  }
  groups.sort((a, b) => b.date.localeCompare(a.date));

  // Totals are recomputed from what actually survived validation, so a dropped
  // work cannot make the header disagree with the grid.
  const works = groups.reduce((sum, group) => sum + group.works.length, 0);
  const bytes = groups.reduce(
    (sum, group) => sum + group.works.reduce((inner, work) => inner + work.bytes, 0),
    0,
  );

  const manifest: Manifest = {
    version: MANIFEST_VERSION,
    generatedAt: asString(raw.generatedAt) ?? '',
    base: asString(raw.base) ?? '',
    totals: { works, bytes },
    groups,
  };
  return { manifest, error: null, warnings };
}

export type ManifestLoadResult =
  | { status: 'ready'; manifest: Manifest; error: null; aborted: false; warnings: string[] }
  | { status: 'empty'; manifest: Manifest; error: null; aborted: false; warnings: string[] }
  | { status: 'error'; manifest: null; error: string; aborted: boolean; warnings: string[] };

export interface LoadManifestOptions {
  base?: string;
  fetchImpl?: typeof fetch;
  signal?: AbortSignal;
}

function isAbortError(error: unknown): boolean {
  return isRecord(error) && error.name === 'AbortError';
}

/** Fetch + validate the manifest. Never throws: failures become an error state. */
export async function loadManifest(options: LoadManifestOptions = {}): Promise<ManifestLoadResult> {
  const url = manifestUrl(options.base);
  const doFetch: typeof fetch | undefined =
    options.fetchImpl ?? (typeof fetch === 'function' ? fetch.bind(globalThis) : undefined);
  if (!doFetch) {
    return {
      status: 'error',
      manifest: null,
      error: '当前环境不支持网络请求，无法加载作品清单。',
      aborted: false,
      warnings: [],
    };
  }
  try {
    const response = await doFetch(url, {
      signal: options.signal,
      headers: { accept: 'application/json' },
    });
    if (!response.ok) {
      const error =
        response.status === 404
          ? MANIFEST_MISSING_MESSAGE
          : `加载作品清单失败：HTTP ${response.status} ${response.statusText}`.trim();
      return { status: 'error', manifest: null, error, aborted: false, warnings: [] };
    }
    let raw: unknown;
    try {
      raw = await response.json();
    } catch {
      return {
        status: 'error',
        manifest: null,
        error: '作品清单不是合法的 JSON，可能生成过程被中断了。',
        aborted: false,
        warnings: [],
      };
    }
    const parsed = parseManifest(raw);
    if (!parsed.manifest) {
      return {
        status: 'error',
        manifest: null,
        error: parsed.error ?? '作品清单无法解析。',
        aborted: false,
        warnings: parsed.warnings,
      };
    }
    if (parsed.manifest.totals.works === 0) {
      return { status: 'empty', manifest: parsed.manifest, error: null, aborted: false, warnings: parsed.warnings };
    }
    return { status: 'ready', manifest: parsed.manifest, error: null, aborted: false, warnings: parsed.warnings };
  } catch (error) {
    if (isAbortError(error) || options.signal?.aborted) {
      return { status: 'error', manifest: null, error: '加载已取消。', aborted: true, warnings: [] };
    }
    const message = error instanceof Error ? error.message : String(error);
    return {
      status: 'error',
      manifest: null,
      error: `无法加载作品清单（${message}）。请检查网络后重试。`,
      aborted: false,
      warnings: [],
    };
  }
}
