/**
 * Local admin studio.
 *
 *   npm run studio        ->  http://127.0.0.1:4180
 *
 * WHY THIS EXISTS: GitHub Pages is static hosting, so the deployed site can
 * never accept an upload. Rather than bolt a backend + object storage + auth
 * onto a static gallery (which forks the repo from the live site), this runs a
 * small server on YOUR machine. The uploaded PSDs are written into `works/`,
 * previews and the layer manifest are regenerated by the very same script CI
 * runs, and 发布 commits + pushes through Git LFS.
 *
 * WHAT IT IS NOT: this is not `vite`, and it does not serve the gallery. It is
 * an admin endpoint plus one page. Never expose it beyond localhost.
 *
 * Security posture (a local server is still a server):
 *   - binds 127.0.0.1 only;
 *   - every mutating request needs the per-run token printed on startup, so
 *     another process or a random web page cannot drive it;
 *   - uploads are validated (extension, size, PSD magic bytes) and written to
 *     fixed, computed paths - the client never supplies a path;
 *   - drafts live in a git-ignored directory until you publish.
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as http from 'node:http';
import * as crypto from 'node:crypto';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import {
  INCOMING_DIR,
  isValidDate,
  listDrafts,
  nextIndex,
  planUploads,
  publishMessage,
  todayIso,
  usedIndexes,
  type DirReader,
} from './upload-plan';
import { SerialTaskQueue } from './queue';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const HOST = '127.0.0.1';
const PORT = Number(process.env.STUDIO_PORT ?? 4180);
const TOKEN = crypto.randomBytes(24).toString('hex');
const PSD_MAGIC = Buffer.from('8BPS', 'ascii');
const LFS_BIN_DIR = process.env.LFS_BIN_DIR ?? '/home/ubuntu/projects/.gocache/bin';
const ASKPASS = process.env.GIT_ASKPASS ?? '';

// --- tiny fs adapter ---------------------------------------------------------

const reader: DirReader = {
  list(dir) {
    try {
      return fs.readdirSync(path.join(ROOT, dir));
    } catch {
      return [];
    }
  },
  isFile(target) {
    try {
      return fs.statSync(path.join(ROOT, target)).isFile();
    } catch {
      return false;
    }
  },
  size(target) {
    try {
      return fs.statSync(path.join(ROOT, target)).size;
    } catch {
      return 0;
    }
  },
};

function abs(relative: string): string {
  const resolved = path.resolve(ROOT, relative);
  if (!resolved.startsWith(ROOT)) throw new Error(`path escapes the project: ${relative}`);
  return resolved;
}

function run(
  command: string,
  args: string[],
  options: { timeoutMs?: number; env?: NodeJS.ProcessEnv } = {},
): Promise<{ code: number; stdout: string; stderr: string; ms: number }> {
  const started = Date.now();
  return new Promise((resolve) => {
    const child = spawn(command, args, {
      cwd: ROOT,
      env: { ...process.env, ...options.env },
    });
    let stdout = '';
    let stderr = '';
    child.stdout.on('data', (chunk) => { stdout += String(chunk); });
    child.stderr.on('data', (chunk) => { stderr += String(chunk); });
    const timer = setTimeout(() => {
      child.kill('SIGTERM');
      stderr += `\n[studio] ${command} timed out after ${options.timeoutMs} ms`;
    }, options.timeoutMs ?? 10 * 60_000);
    child.on('error', (error) => {
      clearTimeout(timer);
      resolve({ code: -1, stdout, stderr: `${stderr}\n${error.message}`, ms: Date.now() - started });
    });
    child.on('close', (code) => {
      clearTimeout(timer);
      resolve({ code: code ?? -1, stdout, stderr, ms: Date.now() - started });
    });
  });
}

// --- manifest rebuild (shares the CI script) ---------------------------------

const manifestQueue = new SerialTaskQueue(() =>
  run('npx', ['tsx', 'scripts/build-manifest.ts'], {
    timeoutMs: 30 * 60_000,
    env: { ...process.env, npm_config_cache: process.env.npm_config_cache ?? `${ROOT}/.npm-cache` },
  }),
);

function readManifestSummary(): unknown {
  try {
    const raw = fs.readFileSync(path.join(ROOT, 'public', 'generated', 'manifest.json'), 'utf8');
    const parsed = JSON.parse(raw) as {
      totals?: { works?: number; bytes?: number };
      groups?: { date: string; works: { name: string; preview?: { thumb?: string } }[] }[];
    };
    if (!parsed.groups) return null;
    return {
      totalWorks: parsed.totals?.works ?? 0,
      groups: parsed.groups.map((group) => ({
        date: group.date,
        works: group.works.map((work) => ({
          name: work.name,
          thumb: work.preview?.thumb ?? null,
        })),
      })),
    };
  } catch {
    return null;
  }
}

function galleryState() {
  const summary = readManifestSummary() as
    | { totalWorks: number; groups: { date: string; works: { name: string; thumb: string | null }[] }[] }
    | null;
  const drafts: {
    date: string;
    entries: { path: string; stem: string; bytes: number; publishTo: string }[];
  }[] = [];

  const incomingRoot = abs(INCOMING_DIR);
  if (fs.existsSync(incomingRoot)) {
    for (const date of fs.readdirSync(incomingRoot).sort()) {
      if (!isValidDate(date)) continue;
      const used = usedIndexes(reader, date);
      const entries = listDrafts(reader, INCOMING_DIR, date).map((draft) => {
        const index = nextIndex(used);
        used.add(index);
        return { ...draft, publishTo: `works/${date}/${index}.psd` };
      });
      if (entries.length > 0) drafts.push({ date, entries });
    }
  }

  return {
    manifest: summary,
    drafts,
    build: manifestQueue.state,
    totals: {
      drafts: drafts.reduce((total, group) => total + group.entries.length, 0),
      works: summary?.totalWorks ?? 0,
    },
  };
}

// --- git publish -------------------------------------------------------------

interface PublishStep {
  step: string;
  ok: boolean;
  detail: string;
}

function gitEnv(): NodeJS.ProcessEnv {
  return {
    ...process.env,
    PATH: `${LFS_BIN_DIR}:${process.env.PATH ?? ''}`,
    ...(ASKPASS ? { GIT_ASKPASS: ASKPASS, GIT_TERMINAL_PROMPT: '0' } : {}),
  };
}

async function publish(): Promise<{ ok: boolean; steps: PublishStep[]; message: string }> {
  const steps: PublishStep[] = [];
  const state = galleryState();
  const pending = state.drafts.flatMap((group) =>
    group.entries.map((entry) => ({ date: group.date, ...entry })),
  );
  if (pending.length === 0) {
    return { ok: false, steps, message: '没有待发布的草稿' };
  }

  // 1. move drafts into their final numbered slot
  const published: { date: string; path: string }[] = [];
  for (const entry of pending) {
    const from = abs(entry.path);
    const to = abs(entry.publishTo);
    if (fs.existsSync(to)) {
      steps.push({ step: 'rename', ok: false, detail: `${entry.publishTo} 已存在，跳过以失败` });
      return { ok: false, steps, message: '目标文件已存在，请刷新后重试' };
    }
    fs.mkdirSync(path.dirname(to), { recursive: true });
    fs.renameSync(from, to);
    published.push({ date: entry.date, path: entry.publishTo });
  }
  steps.push({
    step: 'move',
    ok: true,
    detail: published.map((entry) => `${entry.path} (${(fs.statSync(abs(entry.path)).size / 1024 / 1024).toFixed(1)} MiB)`).join(', '),
  });

  // clean up empty date folders in the draft area
  const incomingRoot = abs(INCOMING_DIR);
  if (fs.existsSync(incomingRoot)) {
    for (const date of fs.readdirSync(incomingRoot)) {
      const dir = path.join(incomingRoot, date);
      try {
        if (fs.readdirSync(dir).length === 0) fs.rmdirSync(dir);
      } catch {
        /* best effort */
      }
    }
  }

  // 2. regenerate previews + manifest (the same script CI runs)
  const build = await manifestQueue.request();
  steps.push({
    step: 'manifest',
    ok: build.code === 0,
    detail: `exit ${build.code} · ${build.ms} ms`,
  });
  if (build.code !== 0) {
    return { ok: false, steps, message: '生成预览/清单失败，已停在这里（文件已移入 works/，没有提交）' };
  }

  // 3. commit and push, through Git LFS
  const message = publishMessage(published.map((entry) => entry.date), published.length);
  const add = await run('git', ['add', '--', 'works'], { env: gitEnv(), timeoutMs: 5 * 60_000 });
  steps.push({ step: 'git add', ok: add.code === 0, detail: `exit ${add.code}` });
  if (add.code !== 0) return { ok: false, steps, message: 'git add 失败' };

  const commit = await run('git', ['commit', '-m', message], { env: gitEnv(), timeoutMs: 60_000 });
  const nothingToCommit = /nothing to commit|no changes added/i.test(commit.stdout + commit.stderr);
  steps.push({
    step: 'git commit',
    ok: commit.code === 0 || nothingToCommit,
    detail: nothingToCommit ? '没有变化可提交' : `exit ${commit.code} · ${firstLine(commit.stdout)}`,
  });
  if (commit.code !== 0 && !nothingToCommit) {
    return { ok: false, steps, message: 'git commit 失败' };
  }

  const branch = await run('git', ['rev-parse', '--abbrev-ref', 'HEAD'], { env: gitEnv(), timeoutMs: 20_000 });
  const currentBranch = branch.stdout.trim() || 'main';
  const push = await run('git', ['push', 'origin', currentBranch], {
    env: gitEnv(),
    timeoutMs: 30 * 60_000, // LFS uploads can be slow
  });
  steps.push({
    step: 'git push',
    ok: push.code === 0,
    detail: push.code === 0 ? firstLine(push.stderr) || 'ok' : lastLine(push.stderr),
  });
  if (push.code !== 0) {
    return { ok: false, steps, message: '已提交但推送失败，请手动 git push（提交是本地安全的）' };
  }

  const state2 = galleryState();
  return {
    ok: true,
    steps,
    message: `已发布 ${published.length} 件作品并推送（当前共 ${state2.totals.works} 件）`,
  };
}

function firstLine(text: string): string {
  return text.split('\n').map((line) => line.trim()).filter(Boolean)[0] ?? '';
}

function lastLine(text: string): string {
  return text.split('\n').map((line) => line.trim()).filter(Boolean).pop() ?? '';
}

// --- upload handling ---------------------------------------------------------

async function handleUpload(request: http.IncomingMessage): Promise<{
  status: number;
  body: unknown;
}> {
  const chunks: Buffer[] = [];
  let received = 0;
  const hardLimit = 2 * 1024 * 1024 * 1024; // 2 GiB safety valve
  for await (const chunk of request) {
    received += (chunk as Buffer).length;
    if (received > hardLimit) return { status: 413, body: { error: '请求体过大' } };
    chunks.push(chunk as Buffer);
  }

  const webRequest = new Request('http://127.0.0.1/upload', {
    method: 'POST',
    headers: { 'content-type': request.headers['content-type'] ?? '' },
    body: Buffer.concat(chunks),
  });
  const form = await webRequest.formData();
  const rawDate = form.get('date');
  const date = typeof rawDate === 'string' && rawDate.trim() !== '' ? rawDate.trim() : todayIso();
  if (!isValidDate(date)) {
    return { status: 400, body: { error: `日期格式必须是 YYYY-MM-DD（收到 ${date}）` } };
  }

  const files = form.getAll('files').filter((entry): entry is File => entry instanceof File);
  if (files.length === 0) return { status: 400, body: { error: '没有收到文件' } };

  const plan = planUploads(reader, {
    date,
    fileNames: files.map((file) => file.name),
    sizes: files.map((file) => file.size),
  });

  // `plan.accepted` preserves upload order and holds only accepted files, so we
  // walk the two lists in step rather than searching by name.
  const acceptedSoFar: typeof plan.accepted = [];
  const written: { path: string; original: string; bytes: number }[] = [];
  let position = 0;
  for (const upload of plan.accepted) {
    const file = files[position];
    position += 1;
    if (!file) {
      plan.rejected.push({ ...upload, rejection: '文件在读取时丢失' });
      continue;
    }
    const bytes = Buffer.from(await file.arrayBuffer());
    // Verify the PSD signature rather than trusting the extension.
    if (bytes.length < 4 || !bytes.subarray(0, 4).equals(PSD_MAGIC)) {
      plan.rejected.push({ ...upload, rejection: '不是有效的 PSD（缺少 8BPS 文件头）' });
      continue;
    }
    const target = abs(upload.incomingPath);
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, bytes);
    acceptedSoFar.push(upload);
    written.push({ path: upload.incomingPath, original: upload.original, bytes: bytes.length });
  }

  // Previews are generated in the background; the UI polls status.
  const rebuild = acceptedSoFar.length > 0 ? manifestQueue.request() : null;

  return {
    status: 200,
    body: {
      date,
      saved: written,
      accepted: acceptedSoFar.map((upload) => ({
        path: upload.incomingPath,
        publishTo: '', // assigned at publish time
        original: upload.original,
        bytes: upload.bytes,
      })),
      rejected: plan.rejected.map((upload) => ({
        original: upload.original,
        reason: upload.rejection ?? '未知原因',
      })),
      rebuilding: rebuild !== null,
      gallery: galleryState(),
    },
  };
}

// --- http --------------------------------------------------------------------

function json(response: http.ServerResponse, status: number, body: unknown): void {
  const payload = JSON.stringify(body);
  response.writeHead(status, {
    'content-type': 'application/json; charset=utf-8',
    'content-length': Buffer.byteLength(payload),
    'cache-control': 'no-store',
  });
  response.end(payload);
}

function authorised(request: http.IncomingMessage): boolean {
  const header = request.headers['x-studio-token'];
  const provided = Array.isArray(header) ? header[0] : header;
  const url = new URL(request.url ?? '/', `http://${HOST}`);
  const query = url.searchParams.get('token');
  const candidate = provided ?? query ?? '';
  if (candidate.length !== TOKEN.length) return false;
  return crypto.timingSafeEqual(Buffer.from(candidate), Buffer.from(TOKEN));
}

const server = http.createServer((request, response) => {
  void (async () => {
    const url = new URL(request.url ?? '/', `http://${HOST}`);
    const route = url.pathname;

    try {
      if (request.method === 'GET' && (route === '/' || route === '/index.html')) {
        const html = fs.readFileSync(path.join(ROOT, 'scripts', 'studio', 'page.html'), 'utf8');
        response.writeHead(200, {
          'content-type': 'text/html; charset=utf-8',
          'cache-control': 'no-store',
        });
        response.end(html.replace('__STUDIO_TOKEN__', TOKEN));
        return;
      }

      if (request.method === 'GET' && route === '/api/status') {
        json(response, 200, { ok: true, gallery: galleryState(), today: todayIso() });
        return;
      }

      if (request.method === 'POST' && route === '/api/upload') {
        if (!authorised(request)) return json(response, 403, { error: 'token 无效' });
        const result = await handleUpload(request);
        json(response, result.status, result.body);
        return;
      }

      if (request.method === 'POST' && route === '/api/publish') {
        if (!authorised(request)) return json(response, 403, { error: 'token 无效' });
        const result = await publish();
        json(response, result.ok ? 200 : 500, result);
        return;
      }

      json(response, 404, { error: 'not found' });
    } catch (error) {
      json(response, 500, { error: error instanceof Error ? error.message : String(error) });
    }
  })();
});

server.on('error', (error: NodeJS.ErrnoException) => {
  if (error.code === 'EADDRINUSE') {
    console.error(`\n[studio] 端口 ${PORT} 已被占用。用 STUDIO_PORT=<其他端口> npm run studio 换一个。\n`);
    process.exit(1);
  }
  throw error;
});

server.listen(PORT, HOST, () => {
  console.log(`
  绘画练习图库 · 本地管理端
  ─────────────────────────────────────────────
  打开：  http://${HOST}:${PORT}/?token=${TOKEN}
  仓库：  ${ROOT}
  草稿：  ${INCOMING_DIR}/<日期>/   （未发布，且已被 .gitignore 忽略）
  说明：  仅监听 ${HOST}，只在本机可用。Ctrl+C 退出。
`);
});
